"""QC schema

Revision ID: 86e0f991b78a
Revises: d5e17772cdb9
Create Date: 2025-08-16 23:59:47.234066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e0f991b78a'
down_revision = 'd5e17772cdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('lot_no', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_material_lot_no'), ['lot_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_material_material_code'), ['material_code'], unique=False)

    op.create_table('qc_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ar_no', sa.String(length=40), nullable=True),
    sa.Column('sample_date', sa.DateTime(), nullable=True),
    sa.Column('sampler', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qc_sample', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_sample_ar_no'), ['ar_no'], unique=True)

    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=120), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('textual_limit', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('overall_verdict', sa.String(length=10), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['qc_sample.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id')
    )
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('result_value', sa.Float(), nullable=True),
    sa.Column('result_text', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('tested_by', sa.String(length=100), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['qc_sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_result')
    op.drop_table('coa')
    op.drop_table('specification')
    with op.batch_alter_table('qc_sample', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_sample_ar_no'))

    op.drop_table('qc_sample')
    with op.batch_alter_table('raw_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_material_material_code'))
        batch_op.drop_index(batch_op.f('ix_raw_material_lot_no'))

    op.drop_table('raw_material')
    # ### end Alembic commands ###
