"""Added WarehouseMaterial table

Revision ID: 87712723b64e
Revises: 86e0f991b78a
Create Date: 2025-08-17 11:24:18.458709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87712723b64e'
down_revision = '86e0f991b78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('batch_no', sa.String(length=100), nullable=False),
    sa.Column('quantity_dispatched', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_table('warehouse_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('issued_quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('issued_to', sa.String(length=200), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['warehouse_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse_issue')
    op.drop_table('warehouse_material')
    op.drop_table('warehouse_dispatch')
    # ### end Alembic commands ###
